import { Timer } from '@/components/Timer'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

const BREAK = 5;
const INTIAL_TIME = 25

export default function Home() {
  const [pomodoro, setPomodoro] = useState(INTIAL_TIME);
  const [seconds, setSecond] = useState(0);
  const [ticking, setTicking] = useState(false);
  const [isBreak, setIsBreak] = useState(false)

  const startTimer = () => {
		setTicking((ticking) => !ticking);
	};

  const startClock = () => {
    if(pomodoro === 0 && seconds === 0){
      setIsBreak(!isBreak)
      setPomodoro(isBreak ? BREAK : INTIAL_TIME)
      setTicking((ticking) => !ticking);
    }

    if (seconds === 0) {
			setPomodoro(prev => prev - 1);
			setSecond(59);
      return;
		}
    setSecond((second) => second - 1);
	};

	useEffect(() => {
		const timer = setInterval(() => {
      if (ticking) startClock()
		}, 1000);

		return () => {
			clearInterval(timer);
		};
	}, [pomodoro, seconds, ticking]);

  const reset = () => {
    setTicking(false)
    setPomodoro(INTIAL_TIME)
    setSecond(0)
  }

  return (
    <>
      <Head>
        <title>Pomodoro Timer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={isBreak ? `${styles.main} ${styles.break}` : `${styles.main} ${styles.work}`}>
      <Timer
        time={pomodoro}
        seconds={seconds}
        ticking={ticking}
        startTimer={startTimer}
        reset={reset}
        isBreak={isBreak}
      />
      </main>
    </>
  )
}
